[#10] CI/CD: Deploy and tests
U-Me-Chan/pissychan-front pull request #12
Opened 2021-12-05 19:36 UTC by Oxore

Closes #10 

Теперь на всех ветках с помощью Github Actions будет производиться запуск тестов по пушу в репозиторий.

На ветке `master` кроме прогона тестов будет так же происходить сборка в архив и деплой на инстанс, указанный в переменных окружения Github Actions.

2021-12-05 19:40 UTC, Oxore commented
@ridouchire Хочешь поревьювить?

2021-12-05 19:54 UTC, Oxore commented
После мержа нужно будет в генерируемом `ecosystem.config.js` изменить значение `NODE_ENV` с `development` на `production` в коммите прям на мастере. Сделать это нужно будет одновременно с выключением текущего инстанса, который был запущен руками и без pm2, чтобы они не подрались за порт, поэтому делаться это будет в ветке `master` и отдельно.

2021-12-17 20:23 UTC, ridouchire requested changes

2021-12-17 20:23 UTC, ridouchire commented on .github/workflows/build_and_deploy.yml
> +        echo "npm_package_version=${package_version}" >>.env
А чому не создать dist-файлик с тестовыми значениями и делать один `cp file.dist file` вместо..?

2021-12-19 22:05 UTC, Oxore commented on .github/workflows/build_and_deploy.yml
> +        echo "npm_package_version=${package_version}" >>.env
Я не понимаю как такой файл мог бы выглядеть. Не мог бы ты привести пример содержимого `dist` файла для данного случая?

В общем-то мне нужно не скопировать данные из файла в файл, а сгенерировать. Как можно видеть выше, содержимое всех переменных окружения генерируется из данных из разных мест, потом эти переменные загоняются в файл `.env`. Может ты хочешь, чтобы я сделал скрипт в отдельном файле, который сгенерит этот файл `.env`, и вызывал его здесь, вместо того, чтобы писать этот скрипт прям вот тут в YAML конфиге CI workflow, как сделано сейчас?

2021-12-24 17:39 UTC, ridouchire commented on .github/workflows/build_and_deploy.yml
> +        echo "npm_package_version=${package_version}" >>.env
В контексте решаемой проблемы моё замечение перестало быть актуальным. Извини за потраченное время.

2021-12-24 17:40 UTC, ridouchire approved these changes

2022-01-22 16:22 UTC, merged